### ISSUE TITLE
01 May 2024 - Diversity Equity & Inclusion Special Interest Group Meeting

### ISSUE THREAD

**Issue by PaulaPaul** [finos/DEI-SIG#51]
## Date
20240401 - 12:00pm EST / 5pm GMT

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes
- [x] Community engagement, DEI SIG recruiting, Ambassador engagement: Open Source in Finance Meetups for the DEI SIG (*Sergio, Rimma*) #49 
        - Review open items in GitHub that are in need of owners/collaborators 
- [x] OSFF London participation (*Rimma*) #52 
- [x] Finalize panel discussion for GHC (*Rimma*) #53 
- [x] FINOS Presence at GHC (*Rita*) #41 
- [x] Run of Show for Open Source Day presenters, establish FINOS OSD co-hosts for the event (*Paula*) #53 
- [x] Events Updates and Format (*Paula*) #39 (Theme Builder, Wellington, BBM and more)
- [ ] Metrics and best practices, help wanted! #33 
- [ ] AOB, Q&A & Adjourn (5mins) - Distribute the Agenda and call to action for attendance (TBD)

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items
- [ ] Post new work items and/or updates to items in progress in GitHub

### Meeting Info
Join Zoom Meeting
https://zoom.us/j/94969868675
Meeting ID: 949 6986 8675
Passcode: 184472

**Comment by mimiflynn** [comment]
Mimi Flynn / Morgan Stanley

**Comment by PaulaPaul** [comment]
Paula Paul - Greyshore @PaulaPaul

**Comment by psmulovics** [comment]
Peter Smulovics / Morgan Stanley

**Comment by KaajalAminSharma** [comment]
Kaajal - Citi

**Comment by Perelmuter** [comment]
Rimma - FINOS

**Comment by sergiobettencourt** [comment]
Sérgio Bettencourt, Citi, sergiobettencourt

**Comment by mcleo-d** [comment]
James McLeod - NatWest

**Comment by eteridvalishvili** [comment]
**Action items from the May 1, 2024 DEI SIG meeting:**

**Recap of Previous Meeting and Action Items:**

- Sergio Bettencourt provided a brief recap of the previous meeting’s discussions and action items and discussed driving forward Community Engagement to maximise the impact of the SIG

**Discussion on Ambassador Program and Collaboration Opportunities:**

- Paula Paul introduced the Ambassador program as a means to facilitate event planning and coordination.
- Attendees discussed leveraging existing community connections and partnerships for future events rather than starting from scratch.
- Ashley Siegel- Morgan Stanley’s DEI Lead - discussed MS’ 2024 DEI strategy/imperatives and the opportunity to collaborate with FINOS around common goals

**Updates on DEI Initiatives:**

- Rimma provided updates on the launch of the AI Readiness SIF initiative - potential link to DEI around addressing Bias and the focus on this topic at both OSFF & GHC
- Rimma Perelmuter provided updates on upcoming events, including participation in the Grace Hopper Conference.
- Discussion focused on the SIG’s strategy for event participation and collaboration with other organizations.
- Paula Paul discussed upcoming events, including participation in the Grace Hopper Conference and Open Source Day.
- Ideas were exchanged regarding the SIG’s involvement in these events and potential collaboration opportunities with other organizations.
- The need for a clear strategy and outreach plan for event participation was emphasized.

**Action Items:**

- Rimma to finalize panel discussion participants for the Grace Hopper Conference.
- Paula and Rimma to explore options for the SIG’s physical presence at events without paying for a booth.
- Paula to coordinate with potential hosts for events in Philadelphia during the Grace Hopper Conference.
- Ashley to share a short blurb about the SIG’s participation in upcoming events with her London team.
- Rita to speak on the community call about activating booth participation at events.
- Paula and Rimma to work on event tracks and promotion strategies.
- Kaajal to reach out to potential partners for event planning and come up with strawman DEI event plan
- Peter to seek assistance for the new DEI website and metrics tracking.
- Sergio to follow up on Community Engagement to maximise the impact of the SIG
